(declOntology "actions" ; 
  '() ; super ontologies
  '(
    ; ACTIONS
    (ont.assert isa-parent "action" TOP)
    (ont.assert isa-parent   "LAC_closing" action)
    (ont.assert isa-parent   "act" action)
    (ont.assert isa-parent   "chat_message" action)
;    (ont.assert isa-parent "consider" action)
;    (ont.assert isa-parent "accept" consider)
;    (ont.assert isa-parent "assemble" consider)
;    (ont.assert isa-parent "conclude" consider)
;    (ont.assert isa-parent "release" consider)
;    (ont.assert isa-parent "verify" consider)
    (ont.assert isa-parent   "create" action)
    (ont.assert isa-parent     "createCD" create)
    (ont.assert isa-parent     "save-info" create)
    (ont.assert isa-parent       "put_data" save-info)
    (ont.assert isa-parent         "register" save-info)
    (ont.assert isa-parent           "advertise" register)
    (ont.assert isa-parent           "observe" register)
    (ont.assert isa-parent             "observe_membership" observe)
    (ont.assert isa-parent             "observe_messages" observe)
    (ont.assert isa-parent           "add_observer" register)
    (ont.assert isa-parent           "registerYellowPages" register)
    (ont.assert isa-parent           "register_agentType" register)
    (ont.assert isa-parent           "register_instance" register)
    (ont.assert isa-parent   "destroy" action)
    (ont.assert isa-parent     "delete-info" destroy)
    (ont.assert isa-parent       "deleteDataCD" delete-info)
    (ont.assert isa-parent       "deleteHistoryCD" delete-info)
    (ont.assert isa-parent       "unregister" delete-info)
    (ont.assert isa-parent         "remove_advertisement" unregister)
    (ont.assert isa-parent         "unregister_agentType" unregister)
    (ont.assert isa-parent         "unregister_instance" unregister)
    (ont.assert isa-parent     "deleteCD" destroy)
    (ont.assert isa-parent   "evaluate" action)
    (ont.assert isa-parent   "execute" action)
    (ont.assert isa-parent   "exit" action)
    (ont.assert isa-parent   "forward_message" action)
    (ont.assert isa-parent   "get" action)
    (ont.assert isa-parent     "get-info" get)
    (ont.assert isa-parent       "getAgents" get-info)
    (ont.assert isa-parent         "get_agents_running" getAgents)
    (ont.assert isa-parent         "get_agents_registered" getAgents)
    (ont.assert isa-parent       "getCDs" get-info)
    (ont.assert isa-parent       "getYellowPages" get-info)
    (ont.assert isa-parent       "get_acts" get-info)
    (ont.assert isa-parent       "get_data" get-info)
    (ont.assert isa-parent       "get_history" get-info)
    (ont.assert isa-parent       "get_members" get-info)
    (ont.assert isa-parent       "get_name" get-info)
    (ont.assert isa-parent       "get_ontology" get-info)
    (ont.assert isa-parent       "resolve_url" get-info)
    (ont.assert isa-parent       "search" get-info)
    (ont.assert isa-parent         "find_instance" search)
    (ont.assert isa-parent     "ping" get)
    (ont.assert isa-parent   "gui_action_request" action)
    (ont.assert isa-parent   "inform_users_list" action)
    (ont.assert isa-parent   "invite_to_cd" action)
    (ont.assert isa-parent   "membership_change" action)
    (ont.assert isa-parent     "join_cd" '(membership_change register))
    (ont.assert isa-parent     "withdraw_cd" '(membership_change unregister))
    (ont.assert isa-parent   "new_MenuItem" action)
    (ont.assert isa-parent   "perform" action)
    (ont.assert isa-parent     "method_call" perform)
    (ont.assert isa-parent     "monitor" perform)
    (ont.assert isa-parent   "performative" action)
    (ont.assert isa-parent     "ack" performative)
    (ont.assert isa-parent       "nack" ack)
;    (ont.assert isa-parent     "inform-if" performative)
;    (ont.assert isa-parent     "inform-ref" performative)
    (ont.assert isa-parent     "inform" performative)
    (ont.assert isa-parent       "notify" '(perform inform))
    (ont.assert isa-parent       "cancel" inform)
    (ont.assert isa-parent       "petition" inform)
    (ont.assert isa-parent         "propose" petition)
    (ont.assert isa-parent           "inform-if" propose)
    (ont.assert isa-parent           "inform-ref" propose)
    (ont.assert isa-parent         "request" petition)
    (ont.assert isa-parent           "query-if" request)
    (ont.assert isa-parent           "query-ref" request)
    (ont.assert isa-parent           "cfp" request)
    (ont.assert isa-parent           "discharge" '(destroy request))
    (ont.assert isa-parent           "request-when" request)
    (ont.assert isa-parent       "propagate" inform)
    (ont.assert isa-parent       "proxy" inform)
    (ont.assert isa-parent       "reply" '(ack inform))
    (ont.assert isa-parent         "affirmative-reply" reply)
    (ont.assert isa-parent           "agree" affirmative-reply)
    (ont.assert isa-parent             "accept-proposal" agree)
    (ont.assert isa-parent             "contract" agree)
    (ont.assert isa-parent           "confirm" affirmative-reply)
    (ont.assert isa-parent           "success" '(affirmative-reply propose)) ;DEPRECATED
    (ont.assert isa-parent         "negative-reply" '(nack reply))
    (ont.assert isa-parent           "disconfirm" negative-reply)
    (ont.assert isa-parent           "failure" '(negative-reply propose))
    (ont.assert isa-parent           "not-understood" negative-reply)
    (ont.assert isa-parent           "refuse" negative-reply)
    (ont.assert isa-parent             "reject-proposal" refuse)
    (ont.assert isa-parent           "timeout" negative-reply)
    (ont.assert isa-parent   "physical_act" action)
    (ont.assert isa-parent   "request-persistent" action)
    (ont.assert isa-parent     "request-whenever" '(request request-persistent))
    (ont.assert isa-parent     "subscribe" '(petition request-persistent))
    (ont.assert isa-parent   "request_aka_mac_list" action)
    (ont.assert isa-parent   "request_user_list" action)
    (ont.assert isa-parent   "run" action)
    (ont.assert isa-parent     "run_agent" run)
    (ont.assert isa-parent   "security_agent_users_list" action)
    (ont.assert isa-parent   "security_authenticate" action)
    (ont.assert isa-parent   "security_authorize" action)
    (ont.assert isa-parent   "security_checkAccess" action)
    (ont.assert isa-parent   "security_vote" action)
    (ont.assert isa-parent   "specific_aka_list" action)
    (ont.assert isa-parent   "update" action)
  )
)