(deftboxrel "isa-parent")
(deftboxrel "isa-ancestor"  :base isa-parent   :transitive )
(deftboxrel "isa"           :base isa-ancestor :reflexive )
(deftboxrel "isa-child"     :base isa-parent  :inverse :assignable)
(deftboxrel "isa-decendant" :base isa-child   :transitive )
(decltype "TOP")

(settbox isa-parent "action" TOP)
(settbox isa-parent "LAC_closing" action)
(settbox isa-parent "act" action)
(settbox isa-parent "chat_message" action)
(settbox isa-parent "consider" action)
(settbox isa-parent "accept" consider)
(settbox isa-parent "assemble" consider)
(settbox isa-parent "conclude" consider)
(settbox isa-parent "release" consider)
(settbox isa-parent "verify" consider)
(settbox isa-parent "create" action)
(settbox isa-parent "createCD" create)
(settbox isa-parent "save-info" create)
(settbox isa-parent "put_data" save-info)
(settbox isa-parent "register" save-info)
(settbox isa-parent "advertise" register)
(settbox isa-parent "observe" register)
;
;Why wasn't this here before?
(settbox isa-parent "add_observer" register)
;
(settbox isa-parent "observe_membership" observe)
(settbox isa-parent "observe_messages" observe)
(settbox isa-parent "registerYellowPages" register)
(settbox isa-parent "register_agentType" register)
(settbox isa-parent "register_instance" register)
(settbox isa-parent "destroy" action)
(settbox isa-parent "delete-info" destroy)
(settbox isa-parent "deleteDataCD" delete-info)
(settbox isa-parent "deleteHistoryCD" delete-info)
(settbox isa-parent "unregister" delete-info)
(settbox isa-parent "remove_advertisement" unregister)
(settbox isa-parent "unregister_agentType" unregister)
(settbox isa-parent "unregister_instance" unregister)
(settbox isa-parent "deleteCD" destroy)
(settbox isa-parent "evaluate" action)
(settbox isa-parent "execute" action)
(settbox isa-parent "exit" action)
(settbox isa-parent "forward_message" action)
(settbox isa-parent "get" action)
(settbox isa-parent "get-info" get)
(settbox isa-parent "getAgents" get-info)
(settbox isa-parent "get_agents_running" getAgents)
(settbox isa-parent "get_agents_registered" getAgents)
(settbox isa-parent "getCDs" get-info)
(settbox isa-parent "getYellowPages" get-info)
(settbox isa-parent "get_acts" get-info)
(settbox isa-parent "get_data" get-info)
(settbox isa-parent "get_history" get-info)
(settbox isa-parent "get_members" get-info)
(settbox isa-parent "get_name" get-info)
(settbox isa-parent "get_ontology" get-info)
(settbox isa-parent "resolve_url" get-info)
(settbox isa-parent "search" get-info)
(settbox isa-parent "find_instance" search)
(settbox isa-parent "ping" get)
(settbox isa-parent "gui_action_request" action)
(settbox isa-parent "inform_users_list" action)
(settbox isa-parent "invite_to_cd" action)
(settbox isa-parent "membership_change" action)
(settbox isa-parent "join_cd" '(membership_change register))
(settbox isa-parent "withdraw_cd" '(membership_change unregister))
(settbox isa-parent "new_MenuItem" action)
(settbox isa-parent "perform" action)
(settbox isa-parent "method_call" perform)
(settbox isa-parent "monitor" perform)
(settbox isa-parent "performative" action)
(settbox isa-parent "ack" performative)
(settbox isa-parent "nack" ack)
(settbox isa-parent "inform" performative)
(settbox isa-parent "notify" '(perform inform))
(settbox isa-parent "cancel" inform)
(settbox isa-parent "petition" inform)
(settbox isa-parent "propose" petition)
(settbox isa-parent "query-if" petition)
(settbox isa-parent "request" petition)
(settbox isa-parent "cfp" request)
(settbox isa-parent "discharge" '(destroy request))
(settbox isa-parent "inform-if" request)
(settbox isa-parent "inform-ref" request)
(settbox isa-parent "query-ref" request)
(settbox isa-parent "request-when" request)
(settbox isa-parent "propagate" inform)
(settbox isa-parent "proxy" inform)
(settbox isa-parent "reply" '(ack inform))
(settbox isa-parent "affirmative-reply" reply)
(settbox isa-parent "agree" affirmative-reply)
(settbox isa-parent "accept-proposal" agree)
(settbox isa-parent "contract" agree)
(settbox isa-parent "confirm" affirmative-reply)
(settbox isa-parent "success" '(affirmative-reply propose))
(settbox isa-parent "negative-reply" '(nack reply))
(settbox isa-parent "disconfirm" negative-reply)
(settbox isa-parent "failure" '(negative-reply propose))
(settbox isa-parent "not-understood" negative-reply)
(settbox isa-parent "refuse" negative-reply)
(settbox isa-parent "reject-proposal" refuse)
(settbox isa-parent "timeout" negative-reply)
(settbox isa-parent "physical_act" action)
(settbox isa-parent "request-persistent" action)
(settbox isa-parent "request-whenever" '(request request-persistent))
(settbox isa-parent "subscribe" '(petition request-persistent))
(settbox isa-parent "request_aka_mac_list" action)
(settbox isa-parent "request_user_list" action)
(settbox isa-parent "run" action)
(settbox isa-parent "run_agent" run)
(settbox isa-parent "security_agent_users_list" action)
(settbox isa-parent "security_authenticate" action)
(settbox isa-parent "security_authorize" action)
(settbox isa-parent "security_checkAccess" action)
(settbox isa-parent "security_vote" action)
(settbox isa-parent "specific_aka_list" action)
(settbox isa-parent "update" action)
(settbox isa-parent "event" TOP)
(settbox isa-parent "event_recurring" event)
(settbox isa-parent "event_SCEvent" event)
(settbox isa-parent "event_SCPerformAction" event_SCEvent)
(settbox isa-parent "event_SCStart" event_SCEvent)
(settbox isa-parent "event_SCStop" event_SCEvent)
(settbox isa-parent "event_SCViolation" event_SCEvent)
(settbox isa-parent "event_messageEvent" event)
(settbox isa-parent "event_messageObserved" event_messageEvent)
(settbox isa-parent "event_messageReceived" event_messageEvent)
(settbox isa-parent "event_messageSent" event_messageEvent)
(settbox isa-parent "event_executeable" event)
(settbox isa-parent "event_deferedExecution" event_executeable)
(settbox isa-parent "event_deferedExecutionDelayed" event_deferedExecution)
; /*****************************************/
; /****** States from ObservableEvent ******/
; /*****************************************/
(settbox isa-parent "event_trace" event)
(settbox isa-parent "event_exited" event)
(settbox isa-parent "event_exiting" event)
; /* Message Events */
(settbox isa-parent "event_messageSendFailed" event_messageEvent)
(settbox isa-parent "event_changedCommands" event_messageEvent)
(settbox isa-parent "event_insertedPerformatives" event_messageEvent)
(settbox isa-parent "event_failedPerformativesUpdate" event_messageEvent)
(settbox isa-parent "event_strategyChanged" event_messageEvent)
(settbox isa-parent "event_postString" event_messageEvent)
(settbox isa-parent "event_MessageReceived" event_messageEvent)
(settbox isa-parent "event_chatMessageReceived" event_MessageReceived)
; /* Advertisement Events */
(settbox isa-parent "event_advertisementEvent" event)
(settbox isa-parent "event_AdvertisementAdded" event_advertisementEvent)
(settbox isa-parent "event_AdvertisementRemoved" event_advertisementEvent)
; /* Cooperation Domain Events */
(settbox isa-parent "event_CDEvent" event)
(settbox isa-parent "event_CDMembershipChange" event_CDEvent)
(settbox isa-parent "event_withdrawCD" event_CDMembershipChange)
(settbox isa-parent "event_joinCD" event_CDMembershipChange)
(settbox isa-parent "event_joinCDFailed" event_CDEvent)
(settbox isa-parent "event_getHistoryCD" event_CDEvent)
(settbox isa-parent "event_joinCDRepeated" event_CDEvent)
(settbox isa-parent "event_participantCD" event_CDEvent)
(settbox isa-parent "event_inviteCD" event_CDEvent)
(settbox isa-parent "event_getCDParticipants" event_CDEvent)
(settbox isa-parent "event_updateURLCD" event_CDEvent)
(settbox isa-parent "event_putDataCD" event_CDEvent)
(settbox isa-parent "event_getDataCD" event_CDEvent)
(settbox isa-parent "event_CDNewMember" event_CDEvent)
; /* LAC Events */
(settbox isa-parent "event_LACEvent" event)
(settbox isa-parent "event_closePort" event_LACEvent)
(settbox isa-parent "event_registerInstance" event_LACEvent)
(settbox isa-parent "event_registerInstanceLocal" event_LACEvent)
(settbox isa-parent "event_registerInstanceRemote" event_LACEvent)
(settbox isa-parent "event_unregisterInstance" event_LACEvent)
(settbox isa-parent "event_findInstances" event_LACEvent)
(settbox isa-parent "event_registerType" event_LACEvent)
(settbox isa-parent "event_unregisterType" event_LACEvent)
; /*
;(deftboxrel "considerer")
;(settbox considerer `(request) consider)
;(settbox considerer `(reply) verify)
;(settbox considerer `(propose discharge) release)
;(settbox considerer `(cancel) release)
;(settbox considerer `(reply propose discharge) conclude)
;(settbox considerer `(inform) accept)
; */
