/* Generated By:JavaCC: Do not edit this line. SLParserTokenManager.java */
package jade.semantics.lang.sl.parser;

public class SLParserTokenManager implements SLParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0)
{
   switch (pos)
   {
      case 0:
         if ((active0 & 0xeL) != 0L)
            return 288;
         if ((active0 & 0x140000000L) != 0L)
         {
            jjmatchedKind = 63;
            return 65;
         }
         return -1;
      case 1:
         if ((active0 & 0x140000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 1;
            return 65;
         }
         return -1;
      case 2:
         if ((active0 & 0x140000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 2;
            return 65;
         }
         return -1;
      case 3:
         if ((active0 & 0x40000000L) != 0L)
            return 65;
         if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 3;
            return 65;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0)
{
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 9:
         return jjStartNfaWithStates_0(0, 2, 288);
      case 10:
         return jjStartNfaWithStates_0(0, 3, 288);
      case 32:
         return jjStartNfaWithStates_0(0, 1, 288);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x100000000L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40000000L);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private final int jjMoveStringLiteralDfa1_0(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000000L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private final int jjMoveStringLiteralDfa2_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 76:
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private final int jjMoveStringLiteralDfa3_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 65);
         break;
      case 83:
      case 115:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private final int jjMoveStringLiteralDfa4_0(long old0, long active0)
{
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0); 
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(4, 32, 65);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
private final void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}
private final void jjCheckNAddStates(int start)
{
   jjCheckNAdd(jjnextStates[start]);
   jjCheckNAdd(jjnextStates[start + 1]);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private final int jjMoveNfa_0(int startState, int curPos)
{
   int[] nextStates;
   int startsAt = 0;
   jjnewStateCnt = 288;
   int i = 1;
   jjstateSet[0] = startState;
   int j, kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x7800dcf200000000L & l) != 0L)
                  {
                     if (kind > 63)
                        kind = 63;
                     jjCheckNAdd(65);
                  }
                  else if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 47)
                        kind = 47;
                     jjCheckNAddStates(0, 7);
                  }
                  else if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(0, 1);
                  else if (curChar == 40)
                  {
                     if (kind > 9)
                        kind = 9;
                     jjCheckNAddStates(8, 70);
                  }
                  else if (curChar == 35)
                     jjCheckNAddStates(71, 74);
                  else if (curChar == 45)
                  {
                     if (kind > 63)
                        kind = 63;
                  }
                  else if (curChar == 34)
                     jjCheckNAddStates(75, 77);
                  else if (curChar == 58)
                     jjAddStates(78, 82);
                  else if (curChar == 41)
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  else if (curChar == 63)
                     jjstateSet[jjnewStateCnt++] = 30;
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(83, 88);
                  else if (curChar == 47)
                     jjAddStates(89, 90);
                  else if (curChar == 39)
                     jjCheckNAddTwoStates(62, 63);
                  else if (curChar == 46)
                     jjCheckNAdd(51);
                  else if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 48;
                  else if (curChar == 63)
                     jjAddStates(91, 95);
                  break;
               case 288:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(0, 1);
                  else if (curChar == 41)
                  {
                     if (kind > 10)
                        kind = 10;
                  }
                  break;
               case 0:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(0, 1);
                  break;
               case 1:
                  if (curChar == 41 && kind > 10)
                     kind = 10;
                  break;
               case 3:
               case 5:
                  if (curChar == 34)
                     jjCheckNAddStates(96, 98);
                  break;
               case 4:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(96, 98);
                  break;
               case 7:
                  if (curChar == 34 && kind > 44)
                     kind = 44;
                  break;
               case 8:
                  if (curChar == 35)
                     jjCheckNAdd(9);
                  break;
               case 9:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(9, 7);
                  break;
               case 10:
                  if ((0x7800dcf200000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAdd(11);
                  break;
               case 11:
                  if ((0xfffffcfa00000000L & l) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAdd(11);
                  break;
               case 12:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(13, 14);
                  break;
               case 13:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(13, 14);
                  break;
               case 14:
                  if (curChar == 39 && kind > 44)
                     kind = 44;
                  break;
               case 15:
                  if (curChar == 45 && kind > 44)
                     kind = 44;
                  break;
               case 16:
                  if (curChar == 63)
                     jjAddStates(91, 95);
                  break;
               case 17:
               case 19:
                  if (curChar == 34)
                     jjCheckNAddStates(99, 101);
                  break;
               case 18:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(99, 101);
                  break;
               case 21:
                  if (curChar == 34 && kind > 45)
                     kind = 45;
                  break;
               case 22:
                  if (curChar == 35)
                     jjCheckNAdd(23);
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(23, 21);
                  break;
               case 24:
                  if ((0x7800dcf200000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(25);
                  break;
               case 25:
                  if ((0xfffffcfa00000000L & l) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(25);
                  break;
               case 26:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(27, 28);
                  break;
               case 27:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(27, 28);
                  break;
               case 28:
                  if (curChar == 39 && kind > 45)
                     kind = 45;
                  break;
               case 29:
                  if (curChar == 45 && kind > 45)
                     kind = 45;
                  break;
               case 30:
                  if (curChar == 63)
                     jjCheckNAddStates(102, 107);
                  break;
               case 31:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(108, 111);
                  break;
               case 32:
                  if (curChar == 45 && kind > 46)
                     kind = 46;
                  break;
               case 33:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(34, 35);
                  break;
               case 34:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(34, 35);
                  break;
               case 35:
                  if (curChar == 39 && kind > 46)
                     kind = 46;
                  break;
               case 36:
                  if ((0x7800dcf200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(37);
                  break;
               case 37:
                  if ((0xfffffcfa00000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(37);
                  break;
               case 38:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 39;
                  break;
               case 40:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(112, 115);
                  break;
               case 41:
                  if ((0x7800dcf200000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(42);
                  break;
               case 42:
                  if ((0xfffffcfa00000000L & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(42);
                  break;
               case 43:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(44, 35);
                  break;
               case 44:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(44, 35);
                  break;
               case 45:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddTwoStates(31, 38);
                  break;
               case 46:
                  if (curChar == 63)
                     jjstateSet[jjnewStateCnt++] = 30;
                  break;
               case 47:
                  if (curChar == 48)
                     jjstateSet[jjnewStateCnt++] = 48;
                  break;
               case 49:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjstateSet[jjnewStateCnt++] = 49;
                  break;
               case 50:
                  if (curChar == 46)
                     jjCheckNAdd(51);
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddTwoStates(51, 52);
                  break;
               case 53:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(54);
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(54);
                  break;
               case 55:
               case 57:
                  if (curChar == 34)
                     jjCheckNAddStates(75, 77);
                  break;
               case 56:
                  if ((0xfffffffbffffffffL & l) != 0L)
                     jjCheckNAddStates(75, 77);
                  break;
               case 59:
                  if (curChar == 34 && kind > 62)
                     kind = 62;
                  break;
               case 60:
                  if (curChar == 45 && kind > 63)
                     kind = 63;
                  break;
               case 61:
                  if (curChar == 39)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 62:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(62, 63);
                  break;
               case 63:
                  if (curChar == 39 && kind > 63)
                     kind = 63;
                  break;
               case 64:
                  if ((0x7800dcf200000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(65);
                  break;
               case 65:
                  if ((0xfffffcfa00000000L & l) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(65);
                  break;
               case 66:
                  if (curChar == 47)
                     jjAddStates(89, 90);
                  break;
               case 67:
                  if (curChar == 47)
                     jjCheckNAddStates(116, 118);
                  break;
               case 68:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(116, 118);
                  break;
               case 69:
                  if ((0x2400L & l) != 0L && kind > 5)
                     kind = 5;
                  break;
               case 70:
                  if (curChar == 10 && kind > 5)
                     kind = 5;
                  break;
               case 71:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 70;
                  break;
               case 72:
                  if (curChar == 42)
                     jjCheckNAddTwoStates(73, 74);
                  break;
               case 73:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(73, 74);
                  break;
               case 74:
                  if (curChar == 42)
                     jjAddStates(119, 120);
                  break;
               case 75:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(76, 74);
                  break;
               case 76:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     jjCheckNAddTwoStates(76, 74);
                  break;
               case 77:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 78:
                  if (curChar == 35)
                     jjCheckNAddStates(71, 74);
                  break;
               case 79:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     jjCheckNAddStates(121, 123);
                  break;
               case 80:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 81:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 82:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 81;
                  break;
               case 83:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(83, 84);
                  break;
               case 84:
                  if (curChar == 34 && kind > 64)
                     kind = 64;
                  break;
               case 85:
                  if (curChar != 40)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAddStates(8, 70);
                  break;
               case 86:
                  if ((0x100000600L & l) == 0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  jjCheckNAdd(86);
                  break;
               case 87:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(87, 88);
                  break;
               case 89:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(89, 90);
                  break;
               case 90:
                  if (curChar == 61 && kind > 12)
                     kind = 12;
                  break;
               case 91:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(91, 92);
                  break;
               case 92:
                  if (curChar == 59 && kind > 13)
                     kind = 13;
                  break;
               case 93:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(93, 96);
                  break;
               case 95:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 94;
                  break;
               case 96:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 95;
                  break;
               case 97:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(97, 100);
                  break;
               case 98:
                  if (curChar == 63 && kind > 15)
                     kind = 15;
                  break;
               case 99:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 98;
                  break;
               case 100:
                  if (curChar == 58)
                     jjstateSet[jjnewStateCnt++] = 99;
                  break;
               case 101:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(101, 102);
                  break;
               case 103:
                  if ((0x10100000600L & l) != 0L && kind > 16)
                     kind = 16;
                  break;
               case 104:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(104, 112);
                  break;
               case 106:
                  if ((0x10100000600L & l) != 0L && kind > 17)
                     kind = 17;
                  break;
               case 113:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(113, 114);
                  break;
               case 115:
                  if ((0x10100000600L & l) != 0L && kind > 18)
                     kind = 18;
                  break;
               case 116:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(116, 117);
                  break;
               case 118:
                  if ((0x10100000600L & l) != 0L && kind > 19)
                     kind = 19;
                  break;
               case 119:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(119, 122);
                  break;
               case 121:
                  if ((0x10100000600L & l) != 0L && kind > 20)
                     kind = 20;
                  break;
               case 123:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(123, 126);
                  break;
               case 125:
                  if ((0x10100000600L & l) != 0L && kind > 21)
                     kind = 21;
                  break;
               case 127:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(127, 131);
                  break;
               case 129:
                  if ((0x10100000600L & l) != 0L && kind > 22)
                     kind = 22;
                  break;
               case 132:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(132, 136);
                  break;
               case 134:
                  if ((0x10100000600L & l) != 0L && kind > 23)
                     kind = 23;
                  break;
               case 137:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(137, 140);
                  break;
               case 141:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(141, 145);
                  break;
               case 143:
                  if ((0x10100000600L & l) != 0L && kind > 25)
                     kind = 25;
                  break;
               case 146:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(146, 150);
                  break;
               case 148:
                  if ((0x10100000600L & l) != 0L && kind > 26)
                     kind = 26;
                  break;
               case 151:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(151, 156);
                  break;
               case 153:
                  if ((0x10100000600L & l) != 0L && kind > 27)
                     kind = 27;
                  break;
               case 157:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(157, 162);
                  break;
               case 159:
                  if ((0x10100000600L & l) != 0L && kind > 28)
                     kind = 28;
                  break;
               case 163:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(163, 168);
                  break;
               case 165:
                  if ((0x10100000600L & l) != 0L && kind > 29)
                     kind = 29;
                  break;
               case 169:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(169, 175);
                  break;
               case 171:
                  if ((0x10100000600L & l) != 0L && kind > 31)
                     kind = 31;
                  break;
               case 176:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(176, 177);
                  break;
               case 178:
                  if ((0x10100000600L & l) != 0L && kind > 33)
                     kind = 33;
                  break;
               case 179:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(179, 187);
                  break;
               case 181:
                  if ((0x10100000600L & l) != 0L && kind > 34)
                     kind = 34;
                  break;
               case 188:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(188, 189);
                  break;
               case 190:
                  if ((0x10100000600L & l) != 0L && kind > 35)
                     kind = 35;
                  break;
               case 191:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(191, 196);
                  break;
               case 193:
                  if ((0x10100000600L & l) != 0L && kind > 36)
                     kind = 36;
                  break;
               case 197:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(197, 204);
                  break;
               case 199:
                  if ((0x10100000600L & l) != 0L && kind > 37)
                     kind = 37;
                  break;
               case 205:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(205, 212);
                  break;
               case 207:
                  if ((0x10100000600L & l) != 0L && kind > 38)
                     kind = 38;
                  break;
               case 213:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(213, 220);
                  break;
               case 215:
                  if ((0x10100000600L & l) != 0L && kind > 39)
                     kind = 39;
                  break;
               case 221:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(221, 228);
                  break;
               case 223:
                  if ((0x10100000600L & l) != 0L && kind > 40)
                     kind = 40;
                  break;
               case 229:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(229, 237);
                  break;
               case 231:
                  if ((0x10100000600L & l) != 0L && kind > 41)
                     kind = 41;
                  break;
               case 238:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(238, 247);
                  break;
               case 240:
                  if ((0x10100000600L & l) != 0L && kind > 42)
                     kind = 42;
                  break;
               case 248:
                  if ((0x100000600L & l) != 0L)
                     jjCheckNAddTwoStates(248, 256);
                  break;
               case 257:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAddStates(0, 7);
                  break;
               case 258:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAdd(258);
                  break;
               case 259:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(259, 260);
                  break;
               case 260:
                  if (curChar != 46)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddTwoStates(261, 52);
                  break;
               case 261:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAddTwoStates(261, 52);
                  break;
               case 262:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(262, 50);
                  break;
               case 263:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddTwoStates(263, 264);
                  break;
               case 265:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAdd(266);
                  break;
               case 266:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 50)
                     kind = 50;
                  jjCheckNAdd(266);
                  break;
               case 267:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 268;
                  break;
               case 268:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 269;
                  break;
               case 269:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 270;
                  break;
               case 270:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 271;
                  break;
               case 271:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 272;
                  break;
               case 272:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 273;
                  break;
               case 273:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 274;
                  break;
               case 275:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 276;
                  break;
               case 276:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 277;
                  break;
               case 277:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 278;
                  break;
               case 278:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 279;
                  break;
               case 279:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 280;
                  break;
               case 280:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 281;
                  break;
               case 281:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 282;
                  break;
               case 282:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 283;
                  break;
               case 283:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 53)
                     kind = 53;
                  jjstateSet[jjnewStateCnt++] = 284;
                  break;
               case 285:
                  if ((0x280000000000L & l) != 0L)
                     jjCheckNAddStates(83, 88);
                  break;
               case 286:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAdd(267);
                  break;
               case 287:
                  if ((0x3ff000000000000L & l) != 0L)
                     jjCheckNAddStates(124, 127);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 2:
               case 65:
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(65);
                  break;
               case 4:
                  jjAddStates(96, 98);
                  break;
               case 6:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 5;
                  break;
               case 10:
               case 11:
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAdd(11);
                  break;
               case 13:
                  jjAddStates(128, 129);
                  break;
               case 18:
                  jjAddStates(99, 101);
                  break;
               case 20:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 19;
                  break;
               case 24:
               case 25:
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(25);
                  break;
               case 27:
                  jjAddStates(130, 131);
                  break;
               case 34:
                  jjCheckNAddTwoStates(34, 35);
                  break;
               case 36:
               case 37:
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(37);
                  break;
               case 39:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(40);
                  break;
               case 40:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAddStates(112, 115);
                  break;
               case 41:
               case 42:
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(42);
                  break;
               case 44:
                  jjCheckNAddTwoStates(44, 35);
                  break;
               case 48:
                  if ((0x100000001000000L & l) != 0L)
                     jjCheckNAdd(49);
                  break;
               case 49:
                  if ((0x7e0000007eL & l) == 0L)
                     break;
                  if (kind > 47)
                     kind = 47;
                  jjCheckNAdd(49);
                  break;
               case 52:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(132, 133);
                  break;
               case 56:
                  jjAddStates(75, 77);
                  break;
               case 58:
                  if (curChar == 92)
                     jjstateSet[jjnewStateCnt++] = 57;
                  break;
               case 62:
                  jjAddStates(134, 135);
                  break;
               case 68:
                  jjAddStates(116, 118);
                  break;
               case 73:
                  jjCheckNAddTwoStates(73, 74);
                  break;
               case 75:
               case 76:
                  jjCheckNAddTwoStates(76, 74);
                  break;
               case 79:
                  jjAddStates(121, 123);
                  break;
               case 88:
                  if (curChar == 124 && kind > 11)
                     kind = 11;
                  break;
               case 94:
                  if (curChar == 124 && kind > 14)
                     kind = 14;
                  break;
               case 102:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 103;
                  break;
               case 105:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 106;
                  break;
               case 107:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 105;
                  break;
               case 108:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 107;
                  break;
               case 109:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 108;
                  break;
               case 110:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 109;
                  break;
               case 111:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 110;
                  break;
               case 112:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 111;
                  break;
               case 114:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 115;
                  break;
               case 117:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 118;
                  break;
               case 120:
                  if ((0x8000000080L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 121;
                  break;
               case 122:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 120;
                  break;
               case 124:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 125;
                  break;
               case 126:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 124;
                  break;
               case 128:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 129;
                  break;
               case 130:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 128;
                  break;
               case 131:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 130;
                  break;
               case 133:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 134;
                  break;
               case 135:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 133;
                  break;
               case 136:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 135;
                  break;
               case 138:
                  if ((0x10000000100000L & l) != 0L && kind > 24)
                     kind = 24;
                  break;
               case 139:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 138;
                  break;
               case 140:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 139;
                  break;
               case 142:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 143;
                  break;
               case 144:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 142;
                  break;
               case 145:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 144;
                  break;
               case 147:
                  if ((0x200000002000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 148;
                  break;
               case 149:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 147;
                  break;
               case 150:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 149;
                  break;
               case 152:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 153;
                  break;
               case 154:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 152;
                  break;
               case 155:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 154;
                  break;
               case 156:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 155;
                  break;
               case 158:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 159;
                  break;
               case 160:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 158;
                  break;
               case 161:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 160;
                  break;
               case 162:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 161;
                  break;
               case 164:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 165;
                  break;
               case 166:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 164;
                  break;
               case 167:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 166;
                  break;
               case 168:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 167;
                  break;
               case 170:
                  if ((0x40000000400000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 171;
                  break;
               case 172:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 170;
                  break;
               case 173:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 172;
                  break;
               case 174:
                  if ((0x2000000020000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 173;
                  break;
               case 175:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 174;
                  break;
               case 177:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 178;
                  break;
               case 180:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 181;
                  break;
               case 182:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 180;
                  break;
               case 183:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 182;
                  break;
               case 184:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 183;
                  break;
               case 185:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 184;
                  break;
               case 186:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 185;
                  break;
               case 187:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 186;
                  break;
               case 189:
                  if ((0x1000000010L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 190;
                  break;
               case 192:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 193;
                  break;
               case 194:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 192;
                  break;
               case 195:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 194;
                  break;
               case 196:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 195;
                  break;
               case 198:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 199;
                  break;
               case 200:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 198;
                  break;
               case 201:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 200;
                  break;
               case 202:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 201;
                  break;
               case 203:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 202;
                  break;
               case 204:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 203;
                  break;
               case 206:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 207;
                  break;
               case 208:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 206;
                  break;
               case 209:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 208;
                  break;
               case 210:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 209;
                  break;
               case 211:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 210;
                  break;
               case 212:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 211;
                  break;
               case 214:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 215;
                  break;
               case 216:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 214;
                  break;
               case 217:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 216;
                  break;
               case 218:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 217;
                  break;
               case 219:
                  if ((0x100000001000000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 218;
                  break;
               case 220:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 219;
                  break;
               case 222:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 223;
                  break;
               case 224:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 222;
                  break;
               case 225:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 224;
                  break;
               case 226:
                  if ((0x4000000040000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 225;
                  break;
               case 227:
                  if ((0x800000008000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 226;
                  break;
               case 228:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 227;
                  break;
               case 230:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 231;
                  break;
               case 232:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 230;
                  break;
               case 233:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 232;
                  break;
               case 234:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 233;
                  break;
               case 235:
                  if ((0x1000000010000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 234;
                  break;
               case 236:
                  if ((0x200000002000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 235;
                  break;
               case 237:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 236;
                  break;
               case 239:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 240;
                  break;
               case 241:
                  if ((0x100000001000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 239;
                  break;
               case 242:
                  if ((0x400000004L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 241;
                  break;
               case 243:
                  if ((0x20000000200L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 242;
                  break;
               case 244:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 243;
                  break;
               case 245:
                  if ((0x200000002L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 244;
                  break;
               case 246:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 245;
                  break;
               case 247:
                  if ((0x4000000040L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 246;
                  break;
               case 249:
                  if ((0x2000000020L & l) != 0L && kind > 43)
                     kind = 43;
                  break;
               case 250:
                  if ((0x800000008L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 249;
                  break;
               case 251:
                  if ((0x400000004000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 250;
                  break;
               case 252:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 251;
                  break;
               case 253:
                  if ((0x20000000200000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 252;
                  break;
               case 254:
                  if ((0x2000000020000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 253;
                  break;
               case 255:
                  if ((0x2000000020L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 254;
                  break;
               case 256:
                  if ((0x8000000080000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 255;
                  break;
               case 264:
                  if ((0x2000000020L & l) != 0L)
                     jjAddStates(136, 137);
                  break;
               case 274:
                  if ((0x10000000100000L & l) != 0L)
                     jjstateSet[jjnewStateCnt++] = 275;
                  break;
               case 284:
                  if ((0x7fffffe07fffffeL & l) != 0L && kind > 53)
                     kind = 53;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 2:
               case 65:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 63)
                     kind = 63;
                  jjCheckNAdd(65);
                  break;
               case 4:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(96, 98);
                  break;
               case 10:
               case 11:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 44)
                     kind = 44;
                  jjCheckNAdd(11);
                  break;
               case 13:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(128, 129);
                  break;
               case 18:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(99, 101);
                  break;
               case 24:
               case 25:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 45)
                     kind = 45;
                  jjCheckNAdd(25);
                  break;
               case 27:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(130, 131);
                  break;
               case 34:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(34, 35);
                  break;
               case 36:
               case 37:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(37);
                  break;
               case 41:
               case 42:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 46)
                     kind = 46;
                  jjCheckNAdd(42);
                  break;
               case 44:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(44, 35);
                  break;
               case 56:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(75, 77);
                  break;
               case 62:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(134, 135);
                  break;
               case 68:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(116, 118);
                  break;
               case 73:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(73, 74);
                  break;
               case 75:
               case 76:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjCheckNAddTwoStates(76, 74);
                  break;
               case 79:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     jjAddStates(121, 123);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 288 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   258, 259, 260, 262, 50, 263, 264, 267, 86, 87, 88, 89, 90, 91, 92, 93, 
   96, 97, 100, 101, 102, 104, 112, 113, 114, 116, 117, 119, 122, 123, 126, 127, 
   131, 132, 136, 137, 140, 141, 145, 146, 150, 151, 156, 157, 162, 163, 168, 169, 
   175, 176, 177, 179, 187, 188, 189, 191, 196, 197, 204, 205, 212, 213, 220, 221, 
   228, 229, 237, 238, 247, 248, 256, 79, 80, 82, 83, 56, 58, 59, 3, 8, 
   10, 12, 15, 258, 47, 50, 263, 286, 287, 67, 72, 17, 22, 24, 26, 29, 
   4, 6, 7, 18, 20, 21, 31, 38, 41, 43, 32, 45, 31, 32, 33, 36, 
   40, 32, 33, 36, 68, 69, 71, 75, 77, 79, 80, 82, 259, 260, 262, 50, 
   13, 14, 27, 28, 53, 54, 62, 63, 265, 266, 
};
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, };
public static final String[] lexStateNames = {
   "DEFAULT", 
};
static final long[] jjtoToken = {
   0xc024fffffffffe01L, 0x1L, 
};
static final long[] jjtoSkip = {
   0xfeL, 0x0L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[288];
private final int[] jjstateSet = new int[576];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public SLParserTokenManager(SimpleCharStream stream)
{
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public SLParserTokenManager(SimpleCharStream stream, int lexState)
{
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 288; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  int kind;
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   try { input_stream.backup(0);
      while (curChar <= 13 && (0x2000L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         TokenLexicalActions(matchedToken);
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 16 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                    if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 17 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                    if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 18 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                    if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 19 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                            if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 20 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                    if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 21 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                            if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 22 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                          if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 23 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                          if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 25 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                            if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 26 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                    if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 27 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                    if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 28 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                    if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 29 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                    if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 31 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                   if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 33 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                  if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 34 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                          if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 35 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                          if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 36 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                  if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 37 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                   if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 38 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                   if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 39 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                   if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 40 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                   if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 41 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                   if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      case 42 :
        if (image == null)
            image = new StringBuffer(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
         else
            image.append(new String(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1))));
                                                                           if (matchedToken.image.endsWith("(")) input_stream.backup(1);
         break;
      default : 
         break;
   }
}
}
