/* Generated By:JavaCC: Do not edit this line. SLParserConstants.java */
package jade.semantics.lang.sl.parser;

public interface SLParserConstants {

  int EOF = 0;
  int AOP = 8;
  int OPEN_BRACKET = 9;
  int CLOSE_BRACKET = 10;
  int PIPEKW = 11;
  int EQUALSKW = 12;
  int SEMICOLONKW = 13;
  int METAPIPEKW = 14;
  int METAOPTIONKW = 15;
  int BELIEVEKW = 16;
  int CONTENTKW = 17;
  int UNCERTAINTYKW = 18;
  int INTENTIONKW = 19;
  int PERSISTENTGOALKW = 20;
  int ORKW = 21;
  int ANDKW = 22;
  int NOTKW = 23;
  int SETKW = 24;
  int ALLKW = 25;
  int ANYKW = 26;
  int IOTAKW = 27;
  int SOMEKW = 28;
  int DONEKW = 29;
  int TRUEKW = 30;
  int EQUIVKW = 31;
  int FALSEKW = 32;
  int OBLIGATIONKW = 33;
  int COUNTASKW = 34;
  int INSTFACTKW = 35;
  int FACTKW = 36;
  int ACTIONKW = 37;
  int RESULTKW = 38;
  int EXISTSKW = 39;
  int FORALLKW = 40;
  int IMPLIESKW = 41;
  int FEASIBLEKW = 42;
  int SEQUENCEKW = 43;
  int PARAMETER_NAME = 44;
  int VARIABLE = 45;
  int META_VARIABLE = 46;
  int INTEGER = 47;
  int SIGN = 48;
  int HEX_LITERAL = 49;
  int FLOAT = 50;
  int MANTISSA = 51;
  int EXPONENT = 52;
  int DATE_TIME = 53;
  int YEAR = 54;
  int MONTH = 55;
  int DAY = 56;
  int HOUR = 57;
  int MINUTE = 58;
  int SECOND = 59;
  int MILLISECOND = 60;
  int TYPE_DESIGNATOR = 61;
  int STRING_LITERAL = 62;
  int WORD = 63;
  int BYTES = 64;
  int DEC_LITERAL = 65;
  int QUOTED_WORD = 66;
  int NOT_QUOTED_WORD = 67;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<AOP>",
    "<OPEN_BRACKET>",
    "<CLOSE_BRACKET>",
    "<PIPEKW>",
    "<EQUALSKW>",
    "<SEMICOLONKW>",
    "<METAPIPEKW>",
    "<METAOPTIONKW>",
    "<BELIEVEKW>",
    "<CONTENTKW>",
    "<UNCERTAINTYKW>",
    "<INTENTIONKW>",
    "<PERSISTENTGOALKW>",
    "<ORKW>",
    "<ANDKW>",
    "<NOTKW>",
    "<SETKW>",
    "<ALLKW>",
    "<ANYKW>",
    "<IOTAKW>",
    "<SOMEKW>",
    "<DONEKW>",
    "\"true\"",
    "<EQUIVKW>",
    "\"false\"",
    "<OBLIGATIONKW>",
    "<COUNTASKW>",
    "<INSTFACTKW>",
    "<FACTKW>",
    "<ACTIONKW>",
    "<RESULTKW>",
    "<EXISTSKW>",
    "<FORALLKW>",
    "<IMPLIESKW>",
    "<FEASIBLEKW>",
    "<SEQUENCEKW>",
    "<PARAMETER_NAME>",
    "<VARIABLE>",
    "<META_VARIABLE>",
    "<INTEGER>",
    "<SIGN>",
    "<HEX_LITERAL>",
    "<FLOAT>",
    "<MANTISSA>",
    "<EXPONENT>",
    "<DATE_TIME>",
    "<YEAR>",
    "<MONTH>",
    "<DAY>",
    "<HOUR>",
    "<MINUTE>",
    "<SECOND>",
    "<MILLISECOND>",
    "<TYPE_DESIGNATOR>",
    "<STRING_LITERAL>",
    "<WORD>",
    "<BYTES>",
    "<DEC_LITERAL>",
    "<QUOTED_WORD>",
    "<NOT_QUOTED_WORD>",
  };

}
